Repository ISIS3510-202410-Team37/Flutter, pull requests merged in 2024-05, with the labels that each got.

#123 Create and manage "Add review" view
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/controller/review_controller.dart
  unifood/lib/main.dart
  unifood/lib/repository/offers_repository.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/repository/review_repository.dart
  unifood/lib/repository/shared_preferences.dart
  unifood/lib/utils/routes.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/points/views/points.dart
  unifood/lib/view/profile/points/widgets/restaurant_points_widget.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/profile/preferences/widgets/custom_settings_options_preferences.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/detail/widgets/location_details.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/liked/views/likedRestaurants.dart
  unifood/lib/view/restaurant/offers/views/offers.dart
  unifood/lib/view/restaurant/plateDetail/view/plate_detail.dart
  unifood/lib/view/reviews/create/view/create_review.dart
  unifood/lib/view/reviews/create/widgets/comment_section.dart
  unifood/lib/view/reviews/create/widgets/restaurant_dropdown.dart
  unifood/lib/view/widgets/custom_appbar_builder.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: enhancement, Flutter

#125 fixes to login button
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/widgets/custom_auth_button.dart
  unifood/pubspec.lock
Labels: bug

#130 Reviews fixes and eventual connectivity fixes
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/reviews/create/view/create_review.dart
Labels: enhancement, Flutter

#131 my reviews view implemented
  unifood/lib/controller/review_controller.dart
  unifood/lib/repository/review_repository.dart
  unifood/lib/utils/routes.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/detail/widgets/reviews_section/review_card.dart
  unifood/lib/view/reviews/create/view/create_review.dart
  unifood/lib/view/reviews/create/widgets/comment_section.dart
  unifood/lib/view/reviews/dashboard/view/myreviews.dart
Labels: Flutter

#132 reviews view features
  unifood/lib/controller/review_controller.dart
  unifood/lib/data/firebase_service_adapter.dart
  unifood/lib/model/review_entity.dart
  unifood/lib/repository/review_repository.dart
  unifood/lib/view/reviews/dashboard/view/myreviews.dart
  unifood/lib/view/widgets/custom_appbar_builder.dart
Labels: Flutter

#133 BQ to review screen time
  unifood/lib/repository/analytics_repository.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/points/views/points.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/liked/views/likedRestaurants.dart
  unifood/lib/view/restaurant/offers/views/offers.dart
  unifood/lib/view/restaurant/plateDetail/view/plate_detail.dart
  unifood/lib/view/restaurant/search/views/search_view.dart
  unifood/lib/view/reviews/create/view/create_review.dart
  unifood/lib/view/reviews/dashboard/view/myreviews.dart
Labels: Analytics Engine

#134 Reservation View
  unifood/lib/controller/reservation_controller.dart
  unifood/lib/model/reservation_entity.dart
  unifood/lib/repository/reservation_repository.dart
  unifood/lib/utils/routes.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/reservation/views/restaurant_reservation.dart
Labels: Flutter

#139 suggested_plates BQ implementation
  unifood/lib/controller/plate_controller.dart
  unifood/lib/repository/plate_repository.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/reservation/views/restaurant_reservation.dart
  unifood/lib/view/reviews/create/view/create_review.dart
  unifood/lib/view/reviews/dashboard/view/myreviews.dart
Labels: Flutter, Analytics Engine

#142 Micro optimizations
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/search/views/search_view.dart
Labels: enhancement, Flutter

#147 micro_optimization of login button view
  unifood/lib/view/auth/views/login.dart
Labels: enhancement

#148 Micro Optimization Preferences
  unifood/lib/repository/preferences_repository.dart
Labels: Flutter

#151 minor fixes to myreviews view
  unifood/lib/view/reviews/dashboard/view/myreviews.dart
Labels: bug, Flutter

#152 Refactor plate_repository.dart to fix id assignment bug
  unifood/lib/repository/plate_repository.dart
Labels: bug
