Repository ISIS3510-202410-Team37/Flutter, pull requests merged in 2024-04, with the labels that each got.

#83 Project config
  unifood/lib/data/firebase_service_adapter.dart
  unifood/lib/repository/analytics_repository.dart
  unifood/lib/repository/auth_repository.dart
  unifood/lib/repository/location_repository.dart
  unifood/lib/repository/plate_repository.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/repository/review_repository.dart
  unifood/lib/repository/user_repository.dart
  unifood/lib/styles/dark_theme.dart
  unifood/lib/styles/light_theme.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/plateDetail/view/plate_detail.dart
  unifood/lib/view/restaurant/search/views/search_view.dart
  unifood/lib/view_model/plate_controller.dart
  unifood/lib/view_model/preferences_controller.dart
  unifood/lib/view_model/restaurant_controller.dart
  unifood/lib/view_model/review_controller.dart
  unifood/lib/view_model/user_controller.dart
Labels: enhancement, Backend

#84 Added internet listener and cache to suggestions feature
  unifood/lib/main.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: enhancement, Backend, Analytics Engine

#85 Service Adapter
  unifood/lib/data/firebase_service_adapter.dart
  unifood/lib/repository/preferences_repository.dart
  unifood/pubspec.lock
Labels: Flutter

#87 Eventual Connectivity scenarios, cache and auth bugfix
  unifood/lib/data/firebase_service_adapter.dart
  unifood/lib/repository/auth_repository.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/repository/shared_preferences.dart
  unifood/lib/repository/user_repository.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/plateDetail/view/plate_detail.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: bug, enhancement, Flutter

#88 Eventual Connectivity and shared preferences session
  unifood/lib/controller/offers_controller.dart
  unifood/lib/controller/plate_controller.dart
  unifood/lib/controller/points_controller.dart
  unifood/lib/controller/preferences_controller.dart
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/controller/review_controller.dart
  unifood/lib/controller/user_controller.dart
  unifood/lib/main.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/points/views/points.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/detail/widgets/location_details.dart
  unifood/lib/view/restaurant/detail/widgets/restaurant_info.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/offers/views/offers.dart
  unifood/lib/view/restaurant/plateDetail/view/plate_detail.dart
  unifood/lib/view/restaurant/search/views/search_view.dart
  unifood/lib/view/widgets/custom_appbar_builder.dart
Labels: enhancement, Flutter

#90 Internet connection reactivity and Streams for Concurrency
  unifood/lib/controller/plate_controller.dart
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/controller/review_controller.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/detail/widgets/location_details.dart
  unifood/lib/view/restaurant/detail/widgets/restaurant_info.dart
  unifood/lib/view/restaurant/plateDetail/view/plate_detail.dart
  unifood/lib/view/restaurant/search/views/search_view.dart
Labels: bug, enhancement, Flutter

#91 favorites view eventual connectivity
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
Labels: Flutter

#92 concurrence in restaurants and favorites view
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
Labels: Flutter

#94 Cache Fixes and minor adjustments to the code
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/main.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/plateDetail/widgets/plate_info.dart
  unifood/pubspec.lock
Labels: bug, enhancement, Flutter

#115 Offers, preferences and points
  unifood/lib/utils/routes.dart
  unifood/lib/view/profile/points/views/points.dart
  unifood/lib/view/profile/points/widgets/restaurant_points_widget.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/profile/preferences/widgets/custom_settings_options_preferences.dart
  unifood/lib/view/profile/preferences/widgets/price_range_selector.dart
  unifood/lib/view/profile/preferences/widgets/save_changes_boton.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/offers/views/offers.dart
  unifood/lib/view/widgets/custom_setting_option_builder.dart
Labels: Flutter

#116 Major Bug
  unifood/lib/controller/restaurant_controller.dart
  unifood/lib/main.dart
  unifood/lib/repository/shared_preferences.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/liked/views/likedRestaurants.dart
Labels: bug, enhancement

#117 main changes
  unifood/lib/main.dart
  unifood/pubspec.lock
Labels: Flutter
