Repository ISIS3510-202410-Team37/Flutter, pull requests merged in 2024-03, with the labels that each got.

#17 Add Widgets and restairants filtered view
  unifood/lib/features/restaurant_detail/views/restaurant_detail.dart
  unifood/lib/features/restaurant_detail/widgets/details_bar.dart
  unifood/lib/features/restaurant_detail/widgets/menu_grid.dart
  unifood/lib/features/restaurants_filtered/views/search_view.dart
  unifood/lib/features/restaurants_filtered/widgets/restaurant_card.dart
  unifood/lib/features/restaurants_filtered/widgets/restaurant_logo.dart
  unifood/lib/features/restaurants_filtered/widgets/search_app_bar.dart
  unifood/lib/routes.dart
Labels: Flutter

#25 Preferences View Creation
  .idea/misc.xml
  .idea/vcs.xml
  .idea/workspace.xml
  unifood/assets/Burgers.png
  unifood/assets/GlutenFree.png
  unifood/assets/Nuggets.png
  unifood/assets/NutFree.png
  unifood/assets/Pasta.png
  unifood/assets/SugarFree.png
  unifood/assets/Tacos.png
  unifood/assets/vegan.png
  unifood/lib/features/preferences/views/preferences.dart
  unifood/lib/features/profile/views/profile.dart
  unifood/lib/routes.dart
  unifood/lib/widgets/custom_settings_options.dart
  unifood/lib/widgets/custom_settings_options_preferences.dart
  unifood/pubspec.lock
Labels: Flutter

#26 Fonts, views and assets refactor
  unifood/assets/background_landing.png
  unifood/assets/fonts/Gudea-Regular.ttf
  unifood/assets/fonts/Inika-Regular.ttf
  unifood/assets/fonts/Katibeh-Regular.ttf
  unifood/assets/fonts/KeaniaOne-Regular.ttf
  unifood/assets/fonts/Roboto-Regular.ttf
  unifood/assets/images/Burgers.png
  unifood/assets/images/GlutenFree.png
  unifood/assets/images/Nuggets.png
  unifood/assets/images/NutFree.png
  unifood/assets/images/Pasta.png
  unifood/assets/images/SugarFree.png
  unifood/assets/images/Tacos.png
  unifood/assets/images/background.jpg
  unifood/assets/images/elcarnal_image.jpg
  unifood/assets/images/elcarnal_logo.jpeg
  unifood/assets/images/profile_image.jpg
  unifood/assets/images/vegan.png
  unifood/lib/features/auth/views/landing.dart
  unifood/lib/features/auth/views/login.dart
  unifood/lib/features/auth/views/signup.dart
  unifood/lib/features/preferences/views/preferences.dart
  unifood/lib/features/profile/views/profile.dart
  unifood/lib/features/restaurant_detail/widgets/menu_grid.dart
  unifood/lib/features/restaurant_detail/widgets/restaurant_info.dart
  unifood/lib/features/restaurant_detail/widgets/review_list.dart
  unifood/lib/features/restaurants_filtered/views/search_view.dart
  unifood/lib/main.dart
  unifood/lib/routes.dart
  unifood/lib/widgets/custom_button.dart
  unifood/lib/widgets/custom_textformfield.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: Flutter

#27 Restaurant dashboard view added
  unifood/lib/features/auth/views/landing.dart
  unifood/lib/features/auth/views/login.dart
  unifood/lib/features/auth/views/signup.dart
  unifood/lib/features/preferences/views/preferences.dart
  unifood/lib/features/profile/views/profile.dart
  unifood/lib/features/restaurant_detail/widgets/menu_grid.dart
  unifood/lib/features/restaurant_detail/widgets/review_list.dart
  unifood/lib/features/restaurants/views/restaurants.dart
  unifood/lib/features/restaurants_filtered/views/search_view.dart
  unifood/lib/features/restaurants_filtered/widgets/restaurant_card.dart
  unifood/lib/features/restaurants_filtered/widgets/restaurant_logo.dart
  unifood/lib/routes.dart
  unifood/lib/widgets/custom_circled_button.dart
  unifood/lib/widgets/custom_restaurant.dart
  unifood/lib/widgets/custom_textformfield.dart
Labels: Flutter

#43 Points View
  unifood/assets/images/BW.png
  unifood/assets/images/Randys.jpg
  unifood/assets/images/star.png
  unifood/lib/utils/routes.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/points/views/points.dart
  unifood/lib/view/profile/points/widgets/custom_restaurant_offers.dart
  unifood/lib/view/profile/points/widgets/restaurant_points_widget.dart
  unifood/lib/view/profile/points/widgets/total_points_widget.dart
  unifood/pubspec.lock
Labels: Flutter

#44 Database connection to the menugrid (plates)
  unifood/lib/data/firebase_service.dart
  unifood/lib/model/plate_entity.dart
  unifood/lib/repository/plate_repository.dart
  unifood/lib/view/profile/points/widgets/restaurant_points_widget.dart
  unifood/lib/view/restaurant/detail/widgets/menu_grid.dart
  unifood/lib/view/restaurant/detail/widgets/plate_card.dart
  unifood/lib/view_model/plate_view_model.dart
  unifood/macos/Flutter/GeneratedPluginRegistrant.swift
  unifood/pubspec.lock
  unifood/pubspec.yaml
  unifood/windows/flutter/generated_plugin_registrant.cc
  unifood/windows/flutter/generated_plugins.cmake
Labels: Backend

#45 Offers View Created
  unifood/android/app/build.gradle
  unifood/assets/images/oferta1.png
  unifood/assets/images/oferta2.jpg
  unifood/assets/images/oferta3.png
  unifood/lib/utils/routes.dart
  unifood/lib/view/profile/points/widgets/custom_restaurant_offers.dart
  unifood/lib/view/restaurant/offers/views/offers.dart
  unifood/lib/view/restaurant/offers/widgets/offer_card.dart
  unifood/pubspec.lock
Labels: Flutter

#47 restaurants view connected to DB and refactor of some widgets
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/detail/widgets/restaurant_info.dart
  unifood/lib/view_model/restaurant_view_model.dart
Labels: Flutter, Backend

#48 User profile Adjustment to media query
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/dashboard/widgets/custom_settings_button.dart
  unifood/lib/view/profile/dashboard/widgets/custom_settings_options.dart
Labels: Flutter

#49 Filter Menu
  unifood/assets/images/Burgers.png
  unifood/assets/images/GlutenFree.png
  unifood/assets/images/Nuggets.png
  unifood/assets/images/NutFree.png
  unifood/assets/images/Pasta.png
  unifood/assets/images/SugarFree.png
  unifood/assets/images/Tacos.png
  unifood/assets/images/trendy1.jpg
  unifood/assets/images/trendy2.jpg
  unifood/assets/images/trendy3.png
  unifood/assets/images/vegan.png
  unifood/lib/utils/routes.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/profile/points/views/points.dart
  unifood/lib/view/profile/points/widgets/build_header_points.dart
  unifood/lib/view/profile/points/widgets/restaurant_points_widget.dart
  unifood/lib/view/profile/points/widgets/total_points_widget.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/profile/preferences/widgets/custom_app_bar.dart
  unifood/lib/view/profile/preferences/widgets/custom_settings_options_preferences.dart
  unifood/lib/view/profile/preferences/widgets/price_range_selector.dart
  unifood/lib/view/profile/preferences/widgets/section_header.dart
  unifood/lib/view/profile/preferences/widgets/settings_checkbox_list.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/filtermenu/views/filter_menu.dart
  unifood/lib/view/restaurant/filtermenu/widgets/category_item.dart
  unifood/lib/view/restaurant/filtermenu/widgets/menu_item_card.dart
  unifood/lib/view/restaurant/filtermenu/widgets/trendy_flavor_item.dart
  unifood/lib/view/restaurant/offers/views/offers.dart
  unifood/lib/view/restaurant/offers/widgets/offer_card.dart
  unifood/lib/view/widgets/custom_appbar.dart
  unifood/pubspec.lock
Labels: Flutter

#51 Login Authentication Added
  unifood/android/app/build.gradle
  unifood/android/build.gradle
  unifood/lib/model/user_entity.dart
  unifood/lib/repository/auth.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/auth/widgets/custom_textformfield.dart
  unifood/macos/Flutter/GeneratedPluginRegistrant.swift
  unifood/pubspec.lock
  unifood/pubspec.yaml
  unifood/windows/flutter/generated_plugin_registrant.cc
  unifood/windows/flutter/generated_plugins.cmake
Labels: Flutter, Backend

#53 login fixes with textformfield
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/auth/widgets/custom_textformfield.dart
  unifood/pubspec.lock
Labels: bug, Flutter

#54 Restaurants minor fixes for location features
  unifood/android/app/src/main/AndroidManifest.xml
  unifood/lib/model/restaurant_entity.dart
  unifood/lib/repository/location_repository.dart
  unifood/lib/utils/distance_calculator.dart
  unifood/lib/view/restaurant/detail/widgets/location_details.dart
  unifood/lib/view_model/restaurant_view_model.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: bug, Flutter

#55 User profile DB Connection
  unifood/android/app/src/main/AndroidManifest.xml
  unifood/lib/main.dart
  unifood/lib/model/user_entity.dart
  unifood/lib/repository/auth.dart
  unifood/lib/repository/auth_repositorydart
  unifood/lib/repository/shared_preferences.dart
  unifood/lib/repository/user_repository.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view_model/user_view_model.dart
  unifood/linux/flutter/generated_plugin_registrant.cc
  unifood/linux/flutter/generated_plugins.cmake
  unifood/macos/Flutter/GeneratedPluginRegistrant.swift
  unifood/pubspec.lock
  unifood/pubspec.yaml
  unifood/windows/flutter/generated_plugin_registrant.cc
  unifood/windows/flutter/generated_plugins.cmake
Labels: bug, Flutter

#56 Restaurants Detail connection to database and manage possible errors
  unifood/lib/model/restaurant_entity.dart
  unifood/lib/repository/plate_repository.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/repository/review_repository.dart
  unifood/lib/utils/routes.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/detail/widgets/location_details.dart
  unifood/lib/view/restaurant/detail/widgets/menu_section/plate_card.dart
  unifood/lib/view/restaurant/detail/widgets/reviews_section/review_card.dart
  unifood/lib/view/restaurant/detail/widgets/reviews_section/review_list.dart
  unifood/lib/view/restaurant/favorites/favorites.dart
  unifood/lib/view_model/plate_view_model.dart
  unifood/lib/view_model/restaurant_view_model.dart
  unifood/lib/view_model/review_view_model.dart
Labels: Flutter

#57 Login and signup fixes
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/auth/widgets/custom_textformfield.dart
  unifood/pubspec.lock
Labels: Flutter

#58 small fixes in login UI
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/widgets/custom_textformfield.dart
Labels: Flutter

#60 Smart feature additions
  unifood/lib/model/plate_entity.dart
  unifood/lib/model/user_entity.dart
  unifood/lib/repository/auth_repository.dart
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/repository/user_repository.dart
  unifood/lib/utils/string_utils.dart
  unifood/lib/view/auth/views/login.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/auth/widgets/custom_textformfield.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/profile/dashboard/widgets/custom_settings_options.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/profile/preferences/widgets/custom_settings_options_preferences.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/detail/widgets/details_bar.dart
  unifood/lib/view/restaurant/detail/widgets/location_details.dart
  unifood/lib/view/restaurant/detail/widgets/menu_section/menu_grid.dart
  unifood/lib/view/restaurant/detail/widgets/menu_section/plate_card.dart
  unifood/lib/view/restaurant/detail/widgets/restaurant_info.dart
  unifood/lib/view/restaurant/detail/widgets/reviews_section/review_list.dart
  unifood/lib/view/restaurant/favorites/views/favorites.dart
  unifood/lib/view/restaurant/favorites/widgets/custom_category_button.dart
  unifood/lib/view/restaurant/favorites/widgets/custom_suggested_restaurant.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/filtermenu/views/filter_menu.dart
  unifood/lib/view/restaurant/filtermenu/widgets/category_item.dart
  unifood/lib/view/restaurant/filtermenu/widgets/menu_item_card.dart
  unifood/lib/view/restaurant/filtermenu/widgets/trendy_flavor_item.dart
  unifood/lib/view/widgets/custom_appbar.dart
  unifood/lib/view_model/plate_view_model.dart
  unifood/lib/view_model/restaurant_view_model.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: Flutter, Backend

#61 Users distance from campus BQ
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view_model/restaurant_view_model.dart
  unifood/lib/view_model/user_view_model.dart
  unifood/pubspec.lock
Labels: Flutter, Analytics Engine

#64 Filter restaurants view adjusted and connected
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/dashboard/widgets/custom_restaurant.dart
  unifood/lib/view/restaurant/detail/views/restaurant_detail.dart
  unifood/lib/view/restaurant/filtermenu/views/filter_menu.dart
  unifood/lib/view/restaurant/search/views/search_view.dart
  unifood/lib/view/restaurant/search/widgets/restaurant_card.dart
  unifood/lib/view/restaurant/search/widgets/restaurant_logo.dart
  unifood/lib/view/restaurant/search/widgets/search_app_bar.dart
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: enhancement, Flutter

#66 User profile
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/widgets/custom_appbar_builder.dart
  unifood/pubspec.lock
Labels: bug

#67 Adjustments to smart feature
  unifood/lib/repository/restaurant_repository.dart
  unifood/lib/view/restaurant/favorites/widgets/custom_suggested_restaurant.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view_model/restaurant_view_model.dart
Labels: Backend, Analytics Engine

#68 adjustments to filter view
  unifood/lib/view/restaurant/search/views/search_view.dart
  unifood/lib/view/restaurant/search/widgets/search_app_bar.dart
Labels: enhancement, Flutter

#69 User profile picture
  unifood/lib/repository/user_repository.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
Labels: bug, Flutter

#72 smart_feature fix
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/favorites/widgets/custom_suggested_restaurant.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
Labels: Flutter

#73 Preferences View
  .idea/.gitignore
  .idea/vcs.xml
  unifood/lib/model/preferences_entity.dart
  unifood/lib/repository/preferences_repository.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/profile/preferences/widgets/custom_settings_options_preferences.dart
  unifood/lib/view/profile/preferences/widgets/reset_button.dart
  unifood/lib/view/profile/preferences/widgets/save_changes_boton.dart
  unifood/lib/view/profile/preferences/widgets/settings_checkbox_list.dart
  unifood/lib/view_model/preferences_view_model.dart
Labels: Flutter

#74 Various changes to the UI were made
  unifood/lib/repository/preferences_repository.dart
  unifood/lib/view/auth/widgets/custom_textformfield.dart
  unifood/lib/view/profile/dashboard/views/profile.dart
  unifood/lib/view/restaurant/dashboard/views/restaurants.dart
  unifood/lib/view/restaurant/detail/widgets/menu_section/menu_grid.dart
  unifood/lib/view/restaurant/detail/widgets/restaurant_info.dart
  unifood/lib/view/restaurant/favorites/widgets/custom_suggested_restaurant.dart
  unifood/lib/view/restaurant/favorites/widgets/suggestions_list.dart
  unifood/lib/view/restaurant/search/widgets/search_app_bar.dart
  unifood/lib/view_model/restaurant_view_model.dart
Labels: enhancement, Flutter

#75 Devices Detector BQ
  unifood/lib/repository/devices_repository.dart
  unifood/lib/view/auth/views/signup.dart
  unifood/lib/view/profile/preferences/views/preferences.dart
  unifood/lib/view/profile/preferences/widgets/custom_settings_options_preferences.dart
  unifood/lib/view/widgets/custom_setting_option_builder.dart
  unifood/lib/view/widgets/view_builder.dart
  unifood/macos/Flutter/GeneratedPluginRegistrant.swift
  unifood/pubspec.lock
  unifood/pubspec.yaml
Labels: Flutter
